version: '3.8'

services:
  auth-service:
    build:
      context: ./AuthMicroService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - inventory-network

  product-service:
    build:
      context: ./ProductMicroService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - inventory-network

  sale-service:
    build:
      context: ./SaleMicroService
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - inventory-network

networks:
  inventory-network:
    driver: bridge
